name: 构建并推送镜像

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:  # 手动触发

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 2. 生成元数据（如标签、描述）
      - name: Podman 元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/check_in_zw_v3
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=true

      # 3. 登录容器注册表
      - name: 登录到 GitHub 容器注册表
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 4. 构建并推送镜像
      - name: 构建并推送镜像
        uses: redhat-actions/buildah-build@v2
        with:
          context: .
          containerfiles: ./Containerfile
          image: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      #- name: 推送到 GitHub 容器注册表
      #  uses: redhat-actions/push-to-registry@v2
       # with:
      #    image: ${{ steps.meta.outputs.tags }}
       #   tags: ${{ steps.meta.outputs.tags }}
       #   registry: ghcr.io/${{ github.repository_owner }}